"""
Customer Acquisition Cohort Analysis
Author: Analytics Team
Date: 2026-01-16

This script analyzes customer behavior by cohorts to understand:
- Customer retention over time
- Revenue patterns by acquisition month
- Customer lifetime value by cohort
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

# Set visualization style
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

print("=" * 70)
print("CUSTOMER ACQUISITION COHORT ANALYSIS")
print("=" * 70)

# Load the cleaned data
print("\nLoading cleaned data...")
df = pd.read_parquet('cleaned_ecommerce_data.parquet')
print(f"✓ Data loaded: {len(df):,} transactions from {df['Customer ID'].nunique():,} customers")

# Step 1: Identify customer's first purchase (acquisition date)
print("\n" + "=" * 70)
print("Step 1: Identifying Customer Acquisition Dates")
print("=" * 70)

customer_acquisition = df.groupby('Customer ID')['InvoiceDate'].min().reset_index()
customer_acquisition.columns = ['Customer ID', 'AcquisitionDate']
customer_acquisition['CohortMonth'] = customer_acquisition['AcquisitionDate'].dt.to_period('M')

print(f"\n✓ Identified acquisition dates for {len(customer_acquisition):,} customers")
print(f"  Cohort period: {customer_acquisition['CohortMonth'].min()} to {customer_acquisition['CohortMonth'].max()}")

# Merge acquisition data back to main dataframe
df_cohort = df.merge(customer_acquisition, on='Customer ID', how='left')

# Step 2: Calculate cohort index (months since first purchase)
print("\n" + "=" * 70)
print("Step 2: Calculating Cohort Index")
print("=" * 70)

df_cohort['InvoiceMonth'] = df_cohort['InvoiceDate'].dt.to_period('M')

# Calculate the difference in months
def get_month_diff(start, end):
    """Calculate the number of months between two periods"""
    return (end.year - start.year) * 12 + (end.month - start.month)

df_cohort['CohortIndex'] = df_cohort.apply(
    lambda row: get_month_diff(row['CohortMonth'], row['InvoiceMonth']),
    axis=1
)

print("✓ Cohort index calculated successfully")
print(f"  Range: Month 0 (acquisition) to Month {df_cohort['CohortIndex'].max()}")

# Step 3: Build cohort retention table
print("\n" + "=" * 70)
print("Step 3: Building Cohort Retention Matrix")
print("=" * 70)

# Count unique customers in each cohort-period combination
cohort_data = df_cohort.groupby(['CohortMonth', 'CohortIndex'])['Customer ID'].nunique().reset_index()
cohort_data.columns = ['CohortMonth', 'CohortIndex', 'CustomerCount']

# Pivot to create the cohort matrix
cohort_matrix = cohort_data.pivot(index='CohortMonth', columns='CohortIndex', values='CustomerCount')

# Calculate retention rates (% of original cohort size)
cohort_size = cohort_matrix.iloc[:, 0]  # First column is cohort size
retention_matrix = cohort_matrix.divide(cohort_size, axis=0) * 100

print(f"✓ Cohort matrix created")
print(f"  Shape: {cohort_matrix.shape[0]} cohorts × {cohort_matrix.shape[1]} periods")
print(f"\nSample retention rates (%):")
print(retention_matrix.iloc[:5, :6].round(2))

# Step 4: Calculate revenue by cohort
print("\n" + "=" * 70)
print("Step 4: Analyzing Revenue by Cohort")
print("=" * 70)

revenue_cohort = df_cohort.groupby(['CohortMonth', 'CohortIndex'])['TotalAmount'].sum().reset_index()
revenue_matrix = revenue_cohort.pivot(index='CohortMonth', columns='CohortIndex', values='TotalAmount')

# Calculate average revenue per customer
avg_revenue_matrix = revenue_matrix.divide(cohort_size, axis=0)

print("✓ Revenue analysis completed")
print(f"\nTotal revenue by cohort (first month):")
cohort_first_month_revenue = revenue_matrix.iloc[:, 0].sort_values(ascending=False)
for cohort, revenue in cohort_first_month_revenue.head(5).items():
    print(f"  {cohort}: ${revenue:,.2f}")

# Step 5: Customer Lifetime Value (LTV) by cohort
print("\n" + "=" * 70)
print("Step 5: Calculating Customer Lifetime Value")
print("=" * 70)

# Total revenue generated by each cohort
cohort_ltv = revenue_matrix.sum(axis=1)
cohort_avg_ltv = cohort_ltv / cohort_size

ltv_df = pd.DataFrame({
    'CohortMonth': cohort_avg_ltv.index.astype(str),
    'CohortSize': cohort_size.values,
    'TotalRevenue': cohort_ltv.values,
    'AvgLTV': cohort_avg_ltv.values
})

print("✓ LTV calculated")
print(f"\nTop 5 Cohorts by Average LTV:")
print(ltv_df.sort_values('AvgLTV', ascending=False).head())

# Step 6: Save all cohort data for visualization
print("\n" + "=" * 70)
print("Step 6: Exporting Cohort Data")
print("=" * 70)

# Save retention matrix
retention_matrix_export = retention_matrix.copy()
retention_matrix_export.index = retention_matrix_export.index.astype(str)
retention_matrix_export.columns = [f'Month_{i}' for i in retention_matrix_export.columns]
retention_matrix_export.to_csv('cohort_retention_matrix.csv')
print("✓ Saved: cohort_retention_matrix.csv")

# Save customer count matrix
cohort_matrix_export = cohort_matrix.copy()
cohort_matrix_export.index = cohort_matrix_export.index.astype(str)
cohort_matrix_export.columns = [f'Month_{i}' for i in cohort_matrix_export.columns]
cohort_matrix_export.to_csv('cohort_customer_count.csv')
print("✓ Saved: cohort_customer_count.csv")

# Save revenue matrix
revenue_matrix_export = revenue_matrix.copy()
revenue_matrix_export.index = revenue_matrix_export.index.astype(str)
revenue_matrix_export.columns = [f'Month_{i}' for i in revenue_matrix_export.columns]
revenue_matrix_export.to_csv('cohort_revenue_matrix.csv')
print("✓ Saved: cohort_revenue_matrix.csv")

# Save LTV data
ltv_df.to_csv('cohort_ltv_analysis.csv', index=False)
print("✓ Saved: cohort_ltv_analysis.csv")

# Save detailed transaction-level cohort data (for Tableau)
cohort_detail = df_cohort[['Customer ID', 'Invoice', 'InvoiceDate', 'Quantity',
                            'Price', 'TotalAmount', 'Country', 'AcquisitionDate',
                            'CohortMonth', 'CohortIndex', 'Date']].copy()
cohort_detail['CohortMonth'] = cohort_detail['CohortMonth'].astype(str)
cohort_detail['AcquisitionDate'] = cohort_detail['AcquisitionDate'].dt.date
cohort_detail.to_csv('cohort_detailed_transactions.csv', index=False)
print("✓ Saved: cohort_detailed_transactions.csv")

# Create a summary statistics file
print("\n" + "=" * 70)
print("Step 7: Generating Summary Statistics")
print("=" * 70)

summary_stats = {
    'Metric': [
        'Total Customers',
        'Total Cohorts',
        'Analysis Period (Months)',
        'Average Cohort Size',
        'Overall Retention Rate (Month 1)',
        'Overall Retention Rate (Month 3)',
        'Overall Retention Rate (Month 6)',
        'Average Customer LTV',
        'Total Revenue',
        'Average Revenue per Transaction'
    ],
    'Value': [
        f"{df_cohort['Customer ID'].nunique():,}",
        f"{len(cohort_matrix)}",
        f"{cohort_matrix.shape[1]}",
        f"{cohort_size.mean():.0f}",
        f"{retention_matrix.iloc[:, 1].mean():.2f}%" if len(retention_matrix.columns) > 1 else "N/A",
        f"{retention_matrix.iloc[:, 3].mean():.2f}%" if len(retention_matrix.columns) > 3 else "N/A",
        f"{retention_matrix.iloc[:, 6].mean():.2f}%" if len(retention_matrix.columns) > 6 else "N/A",
        f"${ltv_df['AvgLTV'].mean():.2f}",
        f"${df_cohort['TotalAmount'].sum():,.2f}",
        f"${df_cohort.groupby('Invoice')['TotalAmount'].sum().mean():.2f}"
    ]
}

summary_df = pd.DataFrame(summary_stats)
summary_df.to_csv('cohort_summary_statistics.csv', index=False)
print("✓ Saved: cohort_summary_statistics.csv")

print("\nSummary Statistics:")
print(summary_df.to_string(index=False))

# Calculate month-over-month retention drop
print("\n" + "=" * 70)
print("Step 8: Retention Drop Analysis")
print("=" * 70)

retention_avg = retention_matrix.mean()
retention_change = pd.DataFrame({
    'Month': [f'Month {i}' for i in retention_avg.index],
    'AvgRetention_%': retention_avg.values.round(2),
    'Change_from_previous': [0] + list(np.diff(retention_avg.values).round(2))
})

retention_change.to_csv('cohort_retention_trends.csv', index=False)
print("✓ Saved: cohort_retention_trends.csv")

print("\nAverage Retention by Period:")
print(retention_change.head(12).to_string(index=False))

print("\n" + "=" * 70)
print("COHORT ANALYSIS COMPLETED!")
print("=" * 70)

print("\nKey Insights:")
print(f"1. We analyzed {df_cohort['Customer ID'].nunique():,} customers across {len(cohort_matrix)} cohorts")
print(f"2. Average customer lifetime value: ${ltv_df['AvgLTV'].mean():.2f}")
if len(retention_matrix.columns) > 1:
    print(f"3. Month 1 retention rate: {retention_matrix.iloc[:, 1].mean():.2f}%")
if len(retention_matrix.columns) > 3:
    print(f"4. Month 3 retention rate: {retention_matrix.iloc[:, 3].mean():.2f}%")
print(f"5. Best performing cohort: {ltv_df.sort_values('AvgLTV', ascending=False).iloc[0]['CohortMonth']}")

print("\n✓ All files ready for Tableau and Streamlit visualization!")
